// <auto-generated />
using AustriaSkiResorts.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AustriaSkiResorts.Migrations
{
    [DbContext(typeof(resortContext))]
    partial class resortContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AustriaSkiResorts.Models.resort", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("availableNumberOfTermins");

                    b.Property<string>("country");

                    b.Property<float>("height");

                    b.Property<float>("length");

                    b.Property<string>("longInfo");

                    b.Property<string>("name");

                    b.Property<int>("price");

                    b.Property<string>("shortInfo");

                    b.Property<string>("snowRange");

                    b.Property<string>("urlPicture");

                    b.HasKey("id");

                    b.ToTable("resort");
                });
#pragma warning restore 612, 618
        }
    }
}
